name: codecoverage 

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  codecoverage_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: llvm-tools-preview
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-binutils rustfilt
    - name: Install jq
      run: sudo apt install jq
    - name: Determine coverage
      run: coverage/coverage.bash
      shell: bash
    - name: Extract line coverage percentage
      id: coverage
      run: |
        pct=$(jq '.data[0].totals.lines.percent' target/coverage/export_without_tests.json)
        printf 'pct=%.2f\n' "$pct" >> "$GITHUB_OUTPUT"
    - name: Update coverage badge gist
      if: github.ref == 'refs/heads/master'
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 8b0f5c110cd7a64899e13a45abcc98ff
        filename: etherparse-coverage.json
        label: coverage
        message: ${{ steps.coverage.outputs.pct }}%
        valColorRange: ${{ steps.coverage.outputs.pct }}
        minColorRange: 0
        maxColorRange: 100
